import Head from 'next/head'
import { useProductContext } from '../context/dataService/ProductContext'
import { Container, ContainerCenter } from '../styles/components/Container';
import { Content, Header } from '../styles/components/Content';
export default function Home() {
  const { products } = useProductContext();
  return (
    <div>
      <Head>
        <title>Guitar Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <h2>Guitar Store</h2>
      </Header>
      <ContainerCenter>
        <Container>
          {products.map(product => (
            <Content key={String(product.id)}>
              <img width="300" src={product.url} alt={product.name} />
              <h4>{product.name}</h4>
              <button>Comprar R$ {product.price},00</button>
            </Content>
          ))}
        </Container>
      </ContainerCenter>
    </div>
  )
}
